### ISSUE TITLE
speed comparison

### ISSUE THREAD

**Issue by taolei87** [musyoku/chainer-sru#1]
hi @musyoku 

your implementation is awesome!  I'm very excited about your results!

I noticed there are two main differences between your version and mine:
- you used conv1d() instead of batched matrix multiplication (gemm)
- you used a (batch, dimension, length) shape for U, while i used (length, batch, dimension) instead.

did you compare the speed between yours and my pytorch version? I would love to hear your feedback and see if there's a chance to improve the pytorch version as well.

thanks a lot!

**Comment by musyoku** [comment]
Hi.
I benchmarked to compare speeds.
![result1](https://raw.githubusercontent.com/musyoku/images/master/sru/pytorch-vs-chainer.png)
![result2](https://raw.githubusercontent.com/musyoku/images/master/sru/pytorch-vs-chainer-lstm.png)

**Comment by musyoku** [comment]
>you used conv1d() instead of batched matrix multiplication (gemm)

Originally I used batched matrix multiplication, but this was slow, so I replaced it with conv1d.

**Comment by musyoku** [comment]
This is a benchmark result when using matmul.
![result](https://user-images.githubusercontent.com/15250418/30874661-fc8e4ae0-a32b-11e7-8aea-dc18771884a1.png)

**Comment by musyoku** [comment]
The old version (bad implementation)
```
grad_u = xp.concatenate((grad_uz, grad_b), axis=1)
grad_x = xp.dot(grad_u.transpose((0, 2, 1)), W).transpose((0, 2, 1)) + grad_highway_x

grad_w = xp.broadcast_to(grad_u[..., None, :], (batchsize,) + W.shape + (seq_length,))
grad_w = xp.sum(grad_w * X[:, None, ...], axis=(0, 3))

grad_b = xp.sum(grad_b, axis=(0, 2))
```

Current version

```
tmp= conv_nd.im2col_nd_gpu(grad_u, (1,), (1,), (0,), cover_all=False)
grad_x = xp.tensordot(tmp, W.T[..., None], ((1, 2), (1, 2))).astype(dtype, copy=False).transpose((0, 2, 1)) + grad_highway_x

grad_b = xp.sum(grad_b, axis=(0, 2))

tmp = conv_nd.im2col_nd_gpu(X, (1,), (1,), (0,), cover_all=False)
grad_w = xp.tensordot(grad_u, tmp, ((0, 2), (0, 3))).astype(dtype, copy=False).reshape((feature_dimension * 3, feature_dimension))
```

**Comment by musyoku** [comment]
>you used a (batch, dimension, length) shape for U, while i used (length, batch, dimension) instead.

Chainer treats the first axis of the array as minibatch index.
Since the shape  (*batch*, *dimension*, *length*)  can be regarded as an image with a height of 1 and a width of *length*, conv1d can be applied.

**Comment by taolei87** [comment]
thank you so much for the prompt reply :)  it seems i should try conv1d() in pytorch when i get the chance.
do you mind i share your implementation and test results on my github README? 
thank you again!

**Comment by musyoku** [comment]
No, I don’t.
I wrote CUDA for the first time, so your implementation was very helpful:smile:

**Comment by taolei87** [comment]
cool. thank you!!

**Comment by musyoku** [comment]
I forgot to write, this is the benchmark code.
https://github.com/musyoku/chainer-sru/blob/master/benchmark/taolei87.py
